### ISSUE TITLE
Other way to synchronise a kanban

### ISSUE THREAD

**Issue by rlalleme** [greggigon/my-personal-kanban#28]
I think it would be nice to have other mean to synchronise Kanban, for instance through SSH.

In combination with the enhancement #26 it would make MPK very usefull and useable (portable).

**Comment by aproposnix** [comment]
Webdav would be good as well.  I think a lot of Owncloud users could appreciate being able to sync their own servers.

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
