### ISSUE TITLE
Hash problem in chromium during upload

### ISSUE THREAD

**Issue by awveale** [greggigon/my-personal-kanban#29]
Using my-personal-kanban-0.7.0 and chromium-browser Version 39.0.2171.65 Ubuntu 14.04 (64-bit)

I have a problem with uploading my boards either to the regular cloud or my cloud running my-personal-kanban-local-cloud-0.1.0-standalone.jar

During upload it reports:

Received kanban doesn't validate with Hash. 6b6dd478db228c9bbd33f7ec8989042a <=> d41d8cd98f00b204e9800998ecf8427e

The first hash changes each upload attempt while the second is always the same.

I have tried removing all the boards and creating new empty ones and still have the same problem.  I also tried to remove the local persistent storage, but I am not certain I removed the correct files.

Using Firefox 33 on the same mpk-0.7.0 and local cloud, I have no errors during upload.

I can also download in chromium boards uploaded to my local cloud via Firefox but I cannot upload the same boards again from chromium even if I upload immediately after downloading.

Addendum:
chromium-browser Version 38.0.2125.104 (290379) (32-bit) (openSuse) does upload and download properly.

The problem may be only a 64-bit browser problem.

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
