### ISSUE TITLE
Title in the Tab

### ISSUE THREAD

**Issue by vincentteoh** [greggigon/my-personal-kanban#33]
Hi  greggigon,
I'm not the programmer, I register the account to give you some suggestion.
Overall, it is good personal kanban. I was thinking that, title appear in the tab of browser can change to the "Kanban Name" instead show up the directory link.

Vincent

**Comment by greggigon** [comment]
Good point. I'm on it.

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
