### ISSUE TITLE
Markdown on the Card Detail

### ISSUE THREAD

**Issue by vincentteoh** [greggigon/my-personal-kanban#34]
Hi geggigon,
Vincent here again. I have another thought, could it possible the markdown editor add on? 
It would enhance the rich content, espcially the list points, links, images, etc.

What do you think?

Reference:
http://jbt.github.io/markdown-editor/#bVPLbtswELzzK7ZwANmtLfWcntqkaQMkQNHHKSgQWqQkWiJXIFdWkqL/3l0qcHoIYIIGOZzZ2VmtYP3F0ddpv7sa9BGjNRu41bE3OAf4bBxhVOqTTq6GKdlmGqCxmqZoYXCJzpWCt3BBcaguvIF38AMIIemjBeosNG6wAriMugUdDJiII+h8Di4wtLPMxPuA2oAjAV/JZY2BbKAEmu+Fj29D5vz1/QYSwiNOUOsAqROEECal1HXhISC0iAY0wRwdudAygR+ZtBLcYCOQfaCtsLSYMSyB3lInWCaOyQ5NqdQNYr/lcsXpm+y0QZRtr+OyPSn1kW2JiyJlEq7cWAbf398f9FGnOrqR1Nm6mUJNDsN680cBnK0L447FpuzID+viGrRnHT4qi80H9ZcXv1fqZ+cS8O8OAywp/V53RGM6r6rWUTftyxp9ddhT5Z8z29mc2UbcDZaAK+oDzuAauC44lv372EszKVc7S+XsVH3jYJIEcRtLuETc57hE/k4MwcK6qLO4j4YxWXyMeLA1pUpwz+rVZgtNRA9z5+pOSWwupNFFLS0QGe512maN3LSO/z2Ck5Q8x77AOA5iUK29lLhareAHTU0jc2iEw+veZqJlCu+kBda82qG6Oxw2nF58me1Rx8R555cXXPqti/E/h+LG56MyWKqWx2JEzzaXnB65zodd59pu4EVc02I+M56Oy0M6cSZsaOZx9To4XacSY5vPqhO6suFZaqGH042MJn8BONE4UR4y2A9Y9ynLHdLO2GbQZF+1b3TosdWuesEtKu2TG0ehxgaMJn1qK89Hw4sV+XtL6h8=

Regards,
Vincent

**Comment by greggigon** [comment]
Good idea. Thanks.

**Comment by bear0330** [comment]
It would be great to have a WYSIWYG editor, I think both CKEditor or TinyMCE are great.
I am trying to add this feature to card details editor (with TinyMCE, it's easier), but I don't know how to build this project, so it's difficult to me to add scripts on minified scripts.

**Comment by greggigon** [comment]
You would have clone this repo, modify the code and build the project.
You'll need to build it with Grunt. Once you got Grunt installed:
```shell
grunt build
```

It will create a zip file, however, non-compressed distribution should be in the **dist** folder.

**Comment by dwelsh1** [comment]
Hello @greggigon 

Is this feature still in progress? Any word on 0.9.0 version?

Great job on this tool! Thanks for creating it.

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
