### ISSUE TITLE
Help on Developing

### ISSUE THREAD

**Issue by rodvlopes** [greggigon/my-personal-kanban#36]
Hi, I´ve cloned the repo but wasn´t able to build the app.

I did:
```
npm install -g grunt-cli
npm install
grunt build
```

At the end, the dist directory was created but the app was incomplete. Some files weren´t properly placed at dist/bower_components dir.

Could somebody give some advises on what I am doing wrong?

**Comment by greggigon** [comment]
Run grunt copy:bower_components and all should be good.
You don't need to build it if you want to run it, just download prepared zip from [page here](
http://greggigon.github.io/my-personal-kanban/)
