### ISSUE TITLE
Describe build process in README.md.

### ISSUE THREAD

**Issue by Zagrebelin** [greggigon/my-personal-kanban#37]
I'm new in bower, npm and angular stuff. Can you describe in few words how to build this application? Open app/index.html in browser doesn't work.

**Comment by greggigon** [comment]
Valid point. I do reorganise the project a little bit. Will follow with readme later :)
For now, try:

    bower install
    grunt copy:bower_dependencies

This will copy all the Bower dependencies into right place.
If you would like to build ZIP run:

    grunt dist

That should get you started. I do recommend Bower and Grunt documentation :)

**Comment by sunaku** [comment]
Looks like it was reorganized again; the suggestion didn't work:

```
$ grunt copy:bower_dependencies
Running "copy:bower_dependencies" (copy) task
Verifying property copy.bower_dependencies exists in config...ERROR
>> Unable to process task.
Warning: Required config property "copy.bower_dependencies" missing. Use --force to continue.

Aborted due to warnings.
```

Luckily, running plain old `grunt copy` did the trick instead. :game_die:

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
