### ISSUE TITLE
Where is data like Boards etc saved

### ISSUE THREAD

**Issue by wealthyone** [greggigon/my-personal-kanban#38]
I found your My Personal Kanban.
tried and it is so simple to use. 
can you please help me.
1st, where does it save any info I create like boards etc.
I set one up when it was in my downloads. then moved the main files to my documents and found the setup was missing. Yep I could backup and import, but was now hoping I can use it on a shared folder I have, but would need to have the board setup etc in the same folder.

I checked every folder in my-personal-kanban but could not find it.

Would be great if I could find and put this file in the same folder.

Hope you can help..

thanks very much

Pete

**Comment by greggigon** [comment]
Hi Pete
I replied to your question on Blog in more details.
http://greggigon.com/projects-and-stuff/#comment-3963
Greg
