### ISSUE TITLE
crashing my-personal-kanban by creating kanban with bad name

### ISSUE THREAD

**Issue by DanielBiskup** [greggigon/my-personal-kanban#39]
Dear my-personal-kanban developers,

I just tried to create a new kanban titled:
OpenGL / CG - To learn and do ( !!! )

This caused my-pesonal-kanban to stop working. The same thing happens in both firefox and chrome.

Thank you for developing my-personal-kanban,
Boris

**Comment by greggigon** [comment]
Thanks Boris. 
I think it might have to do with the Angular Router. I'll have a look and get back to you.
To get around the issue, you could remove the Kanban from the local storage and name it with no special characters for now. 
Let me know if you get around the issue.

**Comment by BorisMonth** [comment]
I didn't try. I just renamed the folder I my-personal-kanban is stored in so I so Firefox fould allow me to start over with an empty kanban. I just had one tiny kanban anyway, so it wasn't to bad loosing it.

**Comment by slawkory** [comment]
While ago I have done the same thing as Boris, "/" makes page related to kanban not functional. 

I don't see way to remove kanban without switching to corrupted kamban ( in practice no way to delete from UI).

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
