### ISSUE TITLE
Can't get the Local Cloud storage working

### ISSUE THREAD

**Issue by KoreTeknology** [greggigon/my-personal-kanban#40]
Hi there,
I really appreciate this app, but i still fighting with the cloud.
I have 2 computers, one at the office, the 2d at home. i want to use my own ftp server to store the data.

I set my IP server/folder (777)... and try... no success !
How can i fix this ? thank you :)

if i'm right, the data will be store in json format, on the server itself, and be uploaded to any computer using the access code...

**Comment by greggigon** [comment]
So, MPK stores data in the Browser Storage (https://developer.mozilla.org/en/docs/Web/API/Window/localStorage). This is Browsers API. However, in the current MPK you can set-it-up to use Cloud to store (with Google Cloud or running your own server https://github.com/greggigon/my-personal-kanban-server ). 

You can't get MPK to work with anything else at the moment. I'm working on a new version of MPK, btw.

I hope this helps, unless I misunderstood what you are asking me for :)

**Comment by KoreTeknology** [comment]
ok, thank you :)
