### ISSUE TITLE
Support nested tasks?

### ISSUE THREAD

**Issue by sunrez** [greggigon/my-personal-kanban#42]
Hi,

Would you consider adding support for nested tasks?  This is seriously a big issue for me as a major project or task needs to be split into several smaller tasks.  Tracking the smaller tasks is often times a big deal, and having one visual tile to see it all is very helpful.

Thank you!

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
