### ISSUE TITLE
Column alignment

### ISSUE THREAD

**Issue by pghedges** [greggigon/my-personal-kanban#43]
After upgrading to 0.8 the columns do not stay pinned to the top of the page. Instead, as I move cards between columns, the entire column moves up and down on the page. Please see attached photo.

Viewing this in Safari browser. Chrome does not have this issue. Thanks for any advice in how to make columns remain in one place... besides ditching Safari.

![screen shot 2016-02-26 at 6 36 43 am](https://cloud.githubusercontent.com/assets/17495378/13352523/6c54af50-dc53-11e5-8923-a74380732b51.png)

**Comment by michael1maass** [comment]
put me on the list..

Michael Maass
![bildschirmfoto 2016-03-04 um 18 54 52](https://cloud.githubusercontent.com/assets/5288914/13535537/11306860-e23b-11e5-8ec9-ab3ec7f9f47e.png)

**Comment by greggigon** [comment]
Hey guys
Can you give me more details of Browser/OS versions you are experiencing this problem in?
Also, I did focus on a new look and new implementation of MPK.
Juggling my day job and other commitments makes it a bit hard to complete and release. But, that is one of the reasons I'm not fixing the old version promptly :)
Greg

**Comment by pghedges** [comment]
Thanks, Greg. I'm running Safari 9.0.3 on Mac 10.11.13

**Comment by michael1maass** [comment]
Hi Greg, 

Version 9.0.3 (11601.4.4) on Safari

Mac OS 10.11.13

regards

Michael

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
