### ISSUE TITLE
not working in IE11

### ISSUE THREAD

**Issue by rghanmi** [greggigon/my-personal-kanban#46]
Hi greggigon , 
Thanks a lot for the application , it is the best application that meet my needs!
i have tested in chrome all is ok but it is not woking in IE11.
Have you tried to fix this issue thanks

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
