### ISSUE TITLE
Suggestion: Title preselected for cards

### ISSUE THREAD

**Issue by sambody** [greggigon/my-personal-kanban#47]
Suggestion 1: _When making a new card_, to have the cursor (focus) already in the title field. So one can immediately start to type.

Suggestion 2: Similarly, _when editing an existing card_, to have the title already in edit mode AND selected. 

This would speed up the creation and editing of cards.

**Comment by sunaku** [comment]
So I tried patching this in, but it appears that such auto-focus code already exists in the codebase, labeled as the `focus-me` attribute and the `focusMe()` function.  For some reason, this doesn't work in Firefox.  I'll need to try it with Chrome.

**Comment by winne42** [comment]
I'd also love this feature, it's the only problem I currently have with your software. If it works with Chrome, it would be a good start! :-) :+1:

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
