### ISSUE TITLE
Bootstrap Not Found?

### ISSUE THREAD

**Issue by praveenscience** [greggigon/my-personal-kanban#48]
When I opened the current branch using [RawGit](https://rawgit.com/greggigon/my-personal-kanban/master/app/index.html), I get this:

![image](https://cloud.githubusercontent.com/assets/1830380/15757272/b0583d16-28fc-11e6-8051-180aaa31f338.png)

Did you remove the Bootstrap from the `bower_components` directory or what? :( Unable to test it online.

**Comment by burningalchemist** [comment]
Hi @praveenscience . That's true, some .css and .js files are missing in the repository - you need to install them via bower. Or you can take a look at the fork in my profile, it works with rawgit fine.

Kind regards,
Sergei

**Comment by praveenscience** [comment]
@burningalchemist Ah! That's great!

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
