### ISSUE TITLE
small creen, header covers columns

### ISSUE THREAD

**Issue by wiemmore** [greggigon/my-personal-kanban#49]
the top of the columns where the butons are, is covered by the header containing the kanban board title and the drop down menu's 

this happens when the width is small like on a smartphone, or when the browser on your pc is not full width,

solution: by removing 

content " "

at the 5th occurence of " " in bootstrap.min.css this problem is solved. 

When the width becomes less than the total width of the board title title and the width of dopdownboxes, the overlap is still there, but that is not a real problem.

maybe there is a better way, taking into account that the fix should work for all themes.

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
