### ISSUE TITLE
Standalone KanBan

### ISSUE THREAD

**Issue by minedun6** [greggigon/my-personal-kanban#52]
Is there a way to use the markup of this project but to store it into my database and to use Bootstrap 3 instead the old version ? As well as having the jquery version(the older one)

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
