### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by WiliansMartins** [greggigon/my-personal-kanban#53]
Good afternoon!

First of all I would like to congratulate the My Kanban, it is an optimal tool.

And I wonder if it allows me to share in an internal network the same Kanban?
thank you,

Wilians Martins
São Paulo Brazil

**Comment by greggigon** [comment]
Thanks.
You can share via Cloud or Export/Import.
Have a look at http://www.mypersonalkanban.com/ and https://github.com/greggigon/my-personal-kanban-server
