### ISSUE TITLE
Doubts database

### ISSUE THREAD

**Issue by WiliansMartins** [greggigon/my-personal-kanban#54]
Good afternoon!

Please, I wonder if it's possible I change the kanban storage location so that two people can work on the same database?

I wonder also where is located the database?

Thank you,

Wilians Martins

**Comment by greggigon** [comment]
Hi Wilians
The MPK database is just a Browser Storage. There is a cloud option available, it will store Kanbans in the cloud. You can also use your own cloud server from here: https://github.com/greggigon/my-personal-kanban-server .
If the cloud option is enough for you have a look here: http://www.mypersonalkanban.com/
