### ISSUE TITLE
Columns Minimum Width

### ISSUE THREAD

**Issue by zukoj** [greggigon/my-personal-kanban#55]
I have a board with 10 columns. Due to the fact that the columns resize so that they fill the full size of the window, on my small 14 inch laptop screen the columns become too narrow and the cards it contains have about a word or 2 on each line.
It would be nice to have a minimum width for the columns and have the window be scrollable horizontally and for that width to be configurable. Hopefully that won't mess up the drag-and-drop feature!

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
