### ISSUE TITLE
Request...Sync the app data towards local filesystem - shared environments

### ISSUE THREAD

**Issue by DkYSwe** [greggigon/my-personal-kanban#56]
Hi,

It would be great if a Firefox (any browser) plugin could be developed (if that's required to write to OS filesystem) to save the app data to local file(s). In our business environment, we have the same home directory for multiple Windows environments (Physical/Virtual).

It would be so great if multiple Windows environments could share and syncronize (without corrupt files) towards the same files. Setting up local cloud services etc... is a no go!

Thanks in advance,
Daniel

**Comment by pckhib** [comment]
I've added this functionality in my [fork](https://github.com/pckhib/my-personal-kanban).
There the application runs in a Electron container and saves the data to a local file.

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
