### ISSUE TITLE
Request: Synchronize with Freedcamp

### ISSUE THREAD

**Issue by perchslayer** [greggigon/my-personal-kanban#57]
I am not (yet) a developer or I would help with this request. There is a very good project management solution that has some very powerful free features and very reasonably priced "extra" features. Your solution would be a very nice thing to dovetail with theirs. Just saying...
[https://freedcamp.com/](url)

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
