### ISSUE TITLE
my kanban board disappeared

### ISSUE THREAD

**Issue by PhB13** [greggigon/my-personal-kanban#58]
Hello,
I just erase some data stored by my Firefox browser and all my kanban data disappeared. I didn't upload them in the cloud. How can I restore them ?

Many thanks in advance.

--
Phil

**Comment by CoreyNorris** [comment]
The exact same thing happened to me as well.  Is there any way to recover the data?

**Comment by greggigon** [comment]
Hi Guys
Sorry to be the bearer of bad news, but ... the MPK uses internal browser storage to store your Kanbans. If you clear Browser data (Private data), the Kanbans will disappear. The only way of getting it back would be to restore from previously Exported copy or from Cloud.
