### ISSUE TITLE
Firefox does not know kanban boards after restart

### ISSUE THREAD

**Issue by nettrapper** [greggigon/my-personal-kanban#59]
Sorry ahead for this question. I'm using Firefox Version 51.0.1. After creating a board, saving the link and reopening firefox with the link there are now kanban boards anymore. I viewed the video using the board but did not find that I do something wrong. Using 0.8.0 version.

Maybe I need some config settings in the browser?

**Comment by philiptruax** [comment]
Are you clearing your cache with every restart? The data of the boards is stored inside the browser itself according to the docs.

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
