### ISSUE TITLE
CSS appears to not be applied in IE 11

### ISSUE THREAD

**Issue by RDKeith** [greggigon/my-personal-kanban#61]
Love this setup and want to use it for our SharePoint (yuck) so badly...  however, when I open index.html, it looks like the functionality is there, but the visuals are off.  The columns are very narrow, all the same size, and color schemes do not work. 

All modals, adding / deleting / renaming, on the other hand, appear to work just fine.  Definitely a styling issue!

Any chance this could be addressed?  Or has support for this project come to an end now?

Thanks!

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
