### ISSUE TITLE
Error at open

### ISSUE THREAD

**Issue by fperdigon** [greggigon/my-personal-kanban#62]
Hi, great aplication. My problem is that I imported a corrupted JSON and now the app don work. I think that if I delete the data stored the app will work fine, Iḿ using firefox 52 in linux. Can you say me the place were the data is stored and the file(s) that I must delete. Thanks in advance

**Comment by maheswaranm** [comment]
Data is stored in Local storage. 
You can delete/change that using Firefox developer tools. 

Sample screenshot from my developer tools on firefox. 

<img width="512" alt="image" src="https://user-images.githubusercontent.com/315616/28350494-553052de-6c17-11e7-84ec-bd97813aea55.png">

You might have to enable the storage tab if you are using for the first time. You can do that using the settings button on top right of the developer tools.

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
