### ISSUE TITLE
Drag'n'drop of cards not working on Firefox mobile

### ISSUE THREAD

**Issue by sarimak** [greggigon/my-personal-kanban#63]
I can edit columns, create cards, delete them but cannot drag a card to another column. Perhaps the drag event on mobile device has to be handled differently? Tried both finger and S-Pen stylus, neither of them worked. Android, Firefox mobile 50.1.0, tablet Samsung Galaxy Note 10.1 2014.

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
