### ISSUE TITLE
Show if there is a description

### ISSUE THREAD

**Issue by maderchristian** [greggigon/my-personal-kanban#64]
It would be great if a card (like in Trello) has an indicator that it has more information in it.

**Comment by RonCam** [comment]
Since there's no automatic indicator, I put an 'asterisk' as the last character of the Card Title.
I'm not familiar with _Trello_, so if Greg has a better idea, please chime in!

**Comment by greggigon** [comment]
@madblobfish @RonCam 
Added in the new version:
[https://greggigon.com/my-personal-kanban-2-0/](https://greggigon.com/my-personal-kanban-2-0/)
