### ISSUE TITLE
Where to find the background-color palette definition for cards?

### ISSUE THREAD

**Issue by riidom** [greggigon/my-personal-kanban#65]
Hi,
first of all, this kanban tool is just awesome!
Now I am trying to modify the looks of the dark theme a bit to my likings, and since I am not very good with angular, I fail to find the defined suggestions for the card background colours. If you can give me a hint where I find them, that would be great, thanks.

**Comment by damdam-s** [comment]
@riidom here it is: https://github.com/greggigon/my-personal-kanban/blob/master/app/scripts/controllers/ApplicationController.js#L5

**Comment by riidom** [comment]
Thanks a lot.
