### ISSUE TITLE
New themes (Modern + Notes)

### ISSUE THREAD

**Issue by PowerPlop** [greggigon/my-personal-kanban#68]
I made two themes for personal use, feel free to add them. I also want to mention that it is possible to add addtional text fields (next to "Details")in the "index.html" if you would like to capture other info.

Modern layout

https://pastebin.com/1R0SHaUq

Notes layout

https://pastebin.com/GkHnZgwm

**Comment by djilano** [comment]
Nice, I created a new theme aswell: https://streamable.com/nhekq

**Comment by PowerPlop** [comment]
Wow, looks impressive. Mine is just a redesign of columns and headers. (don't know much about CSS or javascript)

**Comment by djilano** [comment]
Ah oke, I just edited some of the HTML and wrote new CSS for that, and rebinded some of the JS functions to new buttons. If you want I can give you the html/css.

**Comment by PowerPlop** [comment]
Yes, I would like to try your theme! Maybe @greggigon  can include some changes.

**Comment by djilano** [comment]
[KANBAN.zip](https://github.com/greggigon/my-personal-kanban/files/1480338/KANBAN.zip)

**Comment by ronanharris09** [comment]
@djilano Thanks ! I have some struggles to make a theme, you're right, after doing some research I found that the html file needs some modification as well.

**Comment by Datseris** [comment]
So... How do I "install" those `.css` themes? Just putting them in the `styles/themes` folder seems to not be enough.

**Comment by Maujoe** [comment]
@Datseris Seems like you must add an entry to the themes javascript file in the scripts folder with an editor:
`{"name": "ThemeName", "css":"Themefile"}`

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
