### ISSUE TITLE
Automatic card numbering 

### ISSUE THREAD

**Issue by VBota1** [greggigon/my-personal-kanban#69]
Hello,
I would like to be able to activate an optional feature where every new card gets assigned a unique card number.

I have used these feature on other kanban boards and it can be very useful when working with multiple collaborators. 

Example: 
take a look at card 150 
is simpler than 
take a look at the card named "evaluate the implementation effort for 3d GUI"

**Comment by greggigon** [comment]
@VBota1 
I'm no longer supporting this project but I did create a new version with the feature you are requesting implemented.
You can check it in here:
[https://greggigon.com/my-personal-kanban-2-0/](https://greggigon.com/my-personal-kanban-2-0/)
It would be great if you gave it a test drive and let me know what you think.
