### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by betsalel-williamson** [greggigon/my-personal-kanban#71]
I would like to talk to you about wrapping this up in a NW.js app? [https://github.com/nwjs/nw.js](url)

What NW.js does is have the Chromium in addition to the Node.js environments to run web code.

This would allow the application to boot like a regular app for people with minimal change to what you've done.

**Comment by greggigon** [comment]
@betsalel-williamson 
Hi,
I did something similar, pretty much rewritten the app using Electron and React.
You can find the latest version here:
[https://greggigon.com/my-personal-kanban-2-0/](https://greggigon.com/my-personal-kanban-2-0/)
It would be great if you could give it a try and let me know your thoughts.
