### ISSUE TITLE
Feature request: tags

### ISSUE THREAD

**Issue by gargle256** [greggigon/my-personal-kanban#73]
Hi,

do you think it's possible to add tags to items.
the best would be multiple tags.
the cherry on the cake would be an item color defined by the tag color, and in case of multiples tags, the color of the first one.

Thanks a lot for this tool, useful.
Philippe

**Comment by RonCam** [comment]
Not sure if the developer is still following this thread.  If he is, please don't let this comment stop him from responding.

In this kanban, the effect of a single tag (only) may be simulated by changing the background color.  But, having said that ...

There _is_ a firefox/chrome/chromium kanban add-on that can actually put one or more colored priority-tabs placed onto each item, and perhaps the code they are using for that function could be of interest, if it could be used as an example for adding the feature to My Personal Kanban, to avoid having to start from 'scratch'.

The name of the other browser add-on:  _Scrumptious_

However, _Scruptious_ doesn't have the option of sharing data with another session, running on a different device.

**Comment by greggigon** [comment]
@gargle256 @RonCam 
Hi Both, 
As you probably realised, I was not supporting the project for quite a few years now.
However, I just restarted a new version of MPK, MPK2.0 😄 
You can read about it here. 
[https://greggigon.com/my-personal-kanban-2-0/](https://greggigon.com/my-personal-kanban-2-0/)
Would be great if you could give it a try and let me know what you think.
BTW, the new version supports Tags.
