### ISSUE TITLE
Import Does Not Work 

### ISSUE THREAD

**Issue by richardstevenhack** [greggigon/my-personal-kanban#74]
Just installed the current version an hour or so ago.

Created a simple test kanban with four columns, and a couple cards with a couple colors. That all worked fine. Since I'm aware that clearing the browser storage would destroy any kanbans, I tested the export function and exported the test kanban to a directory on the local file system completely outside of Firefox.

I then tried to import, which did not work. Nothing happened. Wondering if I had to switch to it after the import, I closed out the page, cleared the cache, then restarted MPK and redid the import. Still nothing happened.

I am running on openSUSE LEAP 15.1 Linux with Firefox 68.0.1.

This is the contents of the file Test-export.json:

> {
  "name": "Test",
  "numberOfColumns": 4,
  "columns": [
    {
      "name": "Test Column 1",
      "cards": [
        {
          "name": "Second Card Test",
          "details": "Note on the second card",
          "color": "FAFFA1"
        }
      ],
      "settings": {
        "color": null,
        "limit": 20
      }
    },
    {
      "name": "Column 2",
      "cards": [
        {
          "name": "First Card",
          "details": "",
          "color": "FFB5B5"
        }
      ]
    },
    {
      "name": "Column 3",
      "cards": []
    },
    {
      "name": "Column 4",
      "cards": []
    }
  ],
  "archived": [],
  "settings": {}
}

>

**Comment by philiptruax** [comment]
Try refreshing the page immediately after you import. There isn't any indication that the import was successful otherwise.  I just confirmed that the import works on Windows version 68.0.2 64 bit.

**Comment by orcpac7** [comment]
I've tested this on Windows 10, v1903, build 18362.836
In addition to importing, you will need to use the dropdown if you have more than one Kanban, to select the one you just imported.

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
