### ISSUE TITLE
Escape / in kanbanName, because it's used for URIs

### ISSUE THREAD

**Issue by fpesari** [greggigon/my-personal-kanban#75]
Related to #39 but more specific, using slashes in Kanban Names breaks MPK, so when the variable kanbanName is stored, it needs to be escaped (by `encodeURIComponent(kanbanName)` for example), and then when it's shown to the user it needs to be decoded (by `decodeURIComponent(kanbanName)`, for example).

**Comment by greggigon** [comment]
@fpesari 
Hi
The new version which I created doesn't need this as it's not a browser app but OS native app.
You can find it in here:
[https://greggigon.com/my-personal-kanban-2-0/](https://greggigon.com/my-personal-kanban-2-0/)
