### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by K3nn3th2** [greggigon/my-personal-kanban#76]
Hello,

Are you planning to support Android?
That would be awesome.

I'm looking for a small self hosted kanban board app with android support for some time now.
This looks like it could become the thing needed :)

I'll try building it for android hopefully next week according to [these instructions](https://medium.com/@christof.thalmann/convert-angular-project-to-android-apk-in-10-steps-c49e2fddd29) and will let you know the outcome.

Respect

**Comment by greggigon** [comment]
Interesting :)
Let me know how it goes. I have not touched this project for a very long time now.
I would probably rewrite it with a different technology now :)

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
