### ISSUE TITLE
Due Date as well

### ISSUE THREAD

**Issue by dkuruppath** [greggigon/my-personal-kanban#77]
Hi Greg, 
Amazing tool :) Thank you,
I was looking at a good tool to set up Kanban for my developer board. One thing thats really missing as a user for us, is a "Due Date" on per card.

A "User assignment" would have been brilliant as well, though not mandatory.

thank you,

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. Due date (deadline is also now an option on the card) 😄 
Greg
