### ISSUE TITLE
Hosting on a local server & support multiple users

### ISSUE THREAD

**Issue by shankarswamy** [greggigon/my-personal-kanban#79]
If the developer or someone who's familiar with the code base, could tell me which file I should start looking to do the following modification, I would appreciate it.

I would like to host it on the server I run on my machine and have the ability to keep data files separate: for example, the Work related Kanban data and the perosnal kanban data should be in separate folders. Which file should I look at to make this modification?

Thanks!

**Comment by jhermann** [comment]
This is a browser application. The one thing you can do is to put it on a remote filesystem, in different paths.

**Comment by greggigon** [comment]
Hi @shankarswamy 
I've not been supporting this project for more than 5 years now.
I did start a rewrite and had something that will replace the old version.
You can find out more about it at [https://greggigon.com/2020/10/11/my-personal-kanban-2-0-new-version-released/](https://greggigon.com/2020/10/11/my-personal-kanban-2-0-new-version-released/)

**Comment by shankarswamy** [comment]
This is looking good.
Features I would like:
1. Option to choose the installation folder/directory. I run mine from a USB drive that I carry around with me.
2. Ability to load/store each board in a separate file - perhaps a JSON file for each board. This is crucial for security and sharing individual boards.  

Thanks for sharing this useful software with us.
