### ISSUE TITLE
release 0.8.0 not working on firefox or chrome

### ISSUE THREAD

**Issue by rich-coe** [greggigon/my-personal-kanban#80]
I downloaded and extracted release-0.8.0.
When I open file:///...../app/index.html  I only get a blank page. 
I'm using firefox 77.0.1 and I also tried chrome 83.0.4103.116.
I tried master as well and I get the same result.

**Comment by greggigon** [comment]
Hi @rich-coe 
I've not been supporting this project for more than 5 years now.
I did start a rewrite and had something that will replace the old version.
You can find out more about it at [https://greggigon.com/2020/10/11/my-personal-kanban-2-0-new-version-released/](https://greggigon.com/2020/10/11/my-personal-kanban-2-0-new-version-released/)

**Comment by rich-coe** [comment]
Thanks for the update.
