### ISSUE TITLE
feature request - random color on new tasks. (if random color not yet used, even better)

### ISSUE THREAD

**Issue by fullmooninu** [greggigon/my-personal-kanban#81]
feature request - random color on new tasks. (if random color not yet used, even better)

**Comment by greggigon** [comment]
Hi @fullmooninu 
I've not been supporting this project for more than 5 years now.
I did start a rewrite and had something that will replace the old version.
You can find out more about it at [https://greggigon.com/2020/10/11/my-personal-kanban-2-0-new-version-released/](https://greggigon.com/2020/10/11/my-personal-kanban-2-0-new-version-released/)

**Comment by fullmooninu** [comment]
please add a link to the new version in the readme?
