### ISSUE TITLE
Columns deform in non Firefox/Chrome browsers

### ISSUE THREAD

**Issue by clara2g** [greggigon/my-personal-kanban#83]
Hi, I'm trying to use My Personal Canvas in a lightweight web browser but columns move up every time a tag is added
![Screenshot_20200805_111852](https://user-images.githubusercontent.com/7132501/89395636-e2552900-d70d-11ea-8ba6-1350bed37a50.png)
It happens so far in Midori, Epiphany (gnome-browser) Surf, Badwolf and Otter-Browser.
Thank you.

**Comment by greggigon** [comment]
Hi @clara2g 
I've not been supporting this project for more than 5 years now.
I did start a rewrite and had something that will replace the old version.
You can find out more about it at [https://greggigon.com/2020/10/11/my-personal-kanban-2-0-new-version-released/](https://greggigon.com/2020/10/11/my-personal-kanban-2-0-new-version-released/)
