### ISSUE TITLE
CCleaner or version change in Firefox could destroy your information

### ISSUE THREAD

**Issue by MariwanJ** [greggigon/my-personal-kanban#84]
I had a several weeks plans and updating saved on my laptop. Suddenly nothing remained. Since I don't know where the file physically saved .. I didn't make a copy .. 
At the moment my personal kanban is empty! 
What happened to my data? I don' t know .. I thing I ran ccleaner some days before .. and my Firefox updated .. which one caused the issue .. not sure. 
Please consider saving the data under the folder you have the mypersonal-kanban.. by that you could save the whole system using git. 
I had a copy of the system in my private git .. but the data is not there either. 
I hope you can fix that and help in making it better 
Thanks in advance for this wounder full project and your effort.

**Comment by jhermann** [comment]
There is an export menu item saving a JSON file that you can put into git.

**Comment by greggigon** [comment]
Guys, I've not been supporting or updating this project for more than 5 years now.
It is definitely not up to date.
I did start on the rewrite, as a standalone App.
More details in here: [https://greggigon.com/2020/10/11/my-personal-kanban-2-0-new-version-released/](https://greggigon.com/2020/10/11/my-personal-kanban-2-0-new-version-released/)
@MariwanJ sorry that you lost your Boards. The content is saved to the local Browser Storage. It's not persisted to files.
I don't think you will be able to retrieve the content of the Browser upgrade wiped your browser cache, etc.

I would recommend switching to the new version I'm still working on. It saves everything locally in the User home folder.

**Comment by jhermann** [comment]
@greggigon You should place above link somewhere prominently and archive this project then.
