### ISSUE TITLE
load board from a default json asset on the server?

### ISSUE THREAD

**Issue by miller5** [greggigon/my-personal-kanban#85]
I'd like to deploy a my-personal-kanban on my server so that users can use a board for a single-user, not shared, card sorting task.  I'm not at all familiar with angular yet and am stuck at trying to add a default kanban board that can be loaded from the server.  

Mike

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
