### ISSUE TITLE
Great application - could you  please add deadlines to the projects

### ISSUE THREAD

**Issue by felarov** [greggigon/my-personal-kanban#86]
Love the application!

Would be great if there appears an icon / color change when the projects have passed a certain date. On one page you would be able to see for which parts there is a delay compared to the envisaged ready date

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Deadlines are now in there 😄 
Greg
