### ISSUE TITLE
Keep getting error - there was a problem uploading your Kanban

### ISSUE THREAD

**Issue by metasnw** [greggigon/my-personal-kanban#87]
- doing everything by the book (entered Kanban key + Cloud encryption key into Setup)
- but keep getting this on first upload
  ![image](https://user-images.githubusercontent.com/16079655/101793082-b73c7500-3b05-11eb-8a1b-06a39769ee83.png)

Any ideas where to look?

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
