### ISSUE TITLE
if new kanban board name contains "/" character it is going into some loop

### ISSUE THREAD

**Issue by agresum** [greggigon/my-personal-kanban#88]

**Comment by agresum** [comment]
[my-personal-kanban.zip](https://github.com/greggigon/my-personal-kanban/files/5682484/my-personal-kanban.zip)
This is my kanban board which is not working. can you please fix it.

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: [https://github.com/greggigon/mpk-desktop-app](https://github.com/greggigon/mpk-desktop-app).
Greg
